### PR TITLE
🩹 Mobのplaysoundの音の種類を修正

### PR DESCRIPTION
**Pull request by Lapis-LJA**
コール・フルストゥーカ、456ダイス用entityはneutral(中立Mob)の音になってます

### CODE REVIEW

**Review by quikku — APPROVED** [review]
よさそう

**Review by ChenCMD — CHANGES_REQUESTED** [review]
これらの箇所は確認した上でこうなってるって認識で良い？

https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0007.ectoplasm/attack/2.attack.mcfunction#L25
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0019.horus_priest/tick/2.tick.mcfunction#L11
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0021.demon_eye/tick/event/attack.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0022.red_knight/death/2.death.mcfunction#L15
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0046.clock_of_despair/tick/2.tick.mcfunction#L37-L39
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/0_oclock.mcfunction#L12
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_gold/tick.mcfunction#L27
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/gear_silver/tick.mcfunction#L27
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/wall_lazer_clock/vfx.mcfunction#L7
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0057.none_fighter/attack/2.attack.mcfunction#L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/3.missile/1.missile.mcfunction#L16
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0120.convict/player_process/2.main.mcfunction#L17-L18
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0120.convict/tick/3.slash/3.slash_attack1.mcfunction#L8-L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0129.lexiel/tick/skill_magic/3.skill_magic_landing.mcfunction#L11
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0139.blast_eye/death/2.death.mcfunction#L8-L12
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0139.blast_eye/hurt/2.hurt.mcfunction#L8-L11
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0151.recombined/attack/4.def_down.mcfunction#L17
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0153.domination/death/2.death.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0185.tutankhamen/death/2.death.mcfunction#L8-L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0185.tutankhamen/tick/thunder/03.summon_thunder2.mcfunction#L22
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0204_infernal_watcher/hurt/2.hurt.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0204_infernal_watcher/tick/event/attack_strong.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0204_infernal_watcher/tick/event/attack.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0204_infernal_watcher/tick/event/end_frenzy.mcfunction#L8-L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0206.skull_basher/tick/event/step.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0210.aurora_eye/player_process/03.mp_reduction.mcfunction#L11
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0233.honey_flyer/attack/2.attack.mcfunction#L10
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0234.walleye/tick/2.1.search.mcfunction#L30
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0234.walleye/tick/jet_start.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0255.dependence_eye/tick/3.attack.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0262.frestchika/death/3.death_animation.mcfunction#L27
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0262.frestchika/tick/4.gun/3.ready.mcfunction#L19
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0273.hell_blade/attack.mcfunction#L8
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0273.hell_blade/chase/rotate/-9.mcfunction#L8-L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0273.hell_blade/chase/rotate/0.mcfunction#L19
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/0273.hell_blade/unstuck/drop.mcfunction#L12
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/1005.blue_star/attack/5.reset.mcfunction#L9
https://github.com/ProjectTSB/TheSkyBlessing/blob/fix/mob_sound_type/Asset/data/asset/functions/mob/1008.yellow_star/attack/5.reset.mcfunction#L8

**Comment by Lapis-LJA** [comment]
Mobが付与してくる状態異常はplayerって認識でやってる、一部見逃しも入ってたので直します

**Comment by Lapis-LJA** [comment]
これで変更は終わりです

**Review by ChenCMD — APPROVED** [review]

**Pull request merged**
